### ISSUE TITLE
The package nvidia-cuda-toolkit no longer available

### ISSUE THREAD

**Issue by upinarms** [europa502/Installing-Nvidia-drivers-on-Kali-Linux#2]
Great write up overall, but in Step #9 there is listed a deprecated package that is no longer available in the repos:

"Step 9: Now you can install the cuda toolkits and drivers

apt install -y ocl-icd-libopencl1 nvidia-driver **nvidia-cuda-toolkit**"

Fix:
Install the package hashcat-nvidia instead of nvidia-cuda-toolkit.

**Comment by europa502** [comment]
Yes. I know. I'll update once I figure it out.

**Comment by europa502** [comment]
Hey, Sorry for the late reply @upinarms . Thanks for the fix btw. I'll update it.
